export default {
    updateActiveButtonIdAction: "updateActiveButtonIdAction",
    setUserAction: "setUserAction",
    unsetUserAction: "unsetUserAction",
    writePosts: "writePosts",
    clearAllPost: "clearAllPost",
    deletePostAction: "deletePostAction",
    deleteLastPostAction: "deleteLastPostAction",
    postModalWindowAction: "postModalWindowAction",
    addLikedPostAction: "addLikedPostAction",
    setLikedPostAction: "setLikedPostAction",
    setBestPostsAction: "setBestPostsAction",
    addSubToUserAction: "addSubToUserAction",
    removeSubFromUserAction: "removeSubFromUserAction",
    setHeaderAction: "setHeaderAction",
    setContentAction: "setContentAction",
}
